public enum MenuChoice {
    CREATE_CAR,
    SHOW_ALL_CARS,
    SHOW_LUXURY_CARS,
    DELETE_CAR,
    SEARCH_CAR,
    UPDATE_CAR,
    CREATE_RENTER,
    SHOW_ALL_RENTERS,
    DELETE_RENTER,
    SEARCH_RENTER,
    UPDATE_RENTER,
    CREATE_CONTRACT,
    SHOW_ALL_FULL_CONTRACTS,
    QUIT
}
